#!/bin/bash

#SHELL=/bin/sh
#PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
#set -e 
#source /etc/environment
#source /etc/profile 

@reboot pi /home/pi/autossh-script/cmmc-autossh.sh
